### ISSUE TITLE
Problem after insatlling vtk==9.3.20240921.dev0

### ISSUE THREAD

**Issue by Jimmy-KL** [Kitware/trame-vtklocal#15]
After I installed "vtk==9.3.20240921.dev0", I found that all of the examples in both "vtk" and "pyvista" could not work.
The following example is `demo/basic.py`, nothing is shown in the browser.

![vtklocal_bug2](https://github.com/user-attachments/assets/0ccd49c3-c39d-4f38-b2e7-9f8ae2118509)

The following example is `pyvista/basic.py`, the same problem that nothing is shown in the browser.

![vtklocal_bug](https://github.com/user-attachments/assets/edf5c679-fbb5-42b1-9fce-8a65a1948e5f)

Here are the version of the packages that I installed:
```
vtk:  9.3.20240921.dev0
trame-vtklocal:  0.6.0
trame-vtk:  2.8.10
trame:  3.6.5
trame-server:  3.2.3
```

**Comment by jourdain** [comment]
Just tried on a fresh venv and it is working great. I'm thinking you might have a browser caching issue. Try with another port.

```
Package           Version
----------------- -----------------
aiohappyeyeballs  2.4.3
aiohttp           3.10.9
aiosignal         1.3.1
async-timeout     4.0.3
attrs             24.2.0
contourpy         1.3.0
cycler            0.12.1
fonttools         4.54.1
frozenlist        1.4.1
idna              3.10
kiwisolver        1.4.7
matplotlib        3.9.2
more-itertools    10.5.0
msgpack           1.1.0
multidict         6.1.0
numpy             2.1.2
packaging         24.1
pillow            10.4.0
pip               24.2
pyparsing         3.1.4
python-dateutil   2.9.0.post0
setuptools        69.2.0
six               1.16.0
trame             3.6.5
trame-client      3.3.2
trame-components  2.4.2
trame-server      3.2.3
trame-vtk         2.8.10
trame-vtklocal    0.6.0
trame-vuetify     2.7.1
typing_extensions 4.12.2
vtk               9.3.20240921.dev0
wslink            2.2.1
yarl              1.13.1
```

**Comment by Jimmy-KL** [comment]
@jourdain I tried all the following solutions, but all failed:
- clean the browser cash and use a new port.
- create a new venv using both conda and python venv.
- degrade to use "vtk==9.3.20240810.dev0"
Here is my environment - pyvista is not installed as the basic vtk example` demo/basic.py` failed already:
```
Package          Version
---------------- -----------------
aiohappyeyeballs 2.4.3
aiohttp          3.10.9
aiosignal        1.3.1
attrs            24.2.0
contourpy        1.3.0
cycler           0.12.1
fonttools        4.54.1
frozenlist       1.4.1
idna             3.10
kiwisolver       1.4.7
matplotlib       3.9.2
more-itertools   10.5.0
msgpack          1.1.0
multidict        6.1.0
numpy            2.1.2
packaging        24.1
pillow           10.4.0
pip              24.2
pyparsing        3.1.4
python-dateutil  2.9.0.post0
setuptools       75.1.0
six              1.16.0
trame            3.6.5
trame-client     3.3.2
trame-server     3.2.3
trame-vtk        2.8.10
trame-vtklocal   0.6.0
trame-vuetify    2.7.1
vtk              9.3.20240921.dev0
wheel            0.44.0
wslink           2.2.1
yarl             1.13.1
```
For error information, this is the only error information `JS Error => [object Event]`.

![20241007154257](https://github.com/user-attachments/assets/abafc066-8a6f-497d-9908-f55c397f918f)

Then I'm afraid it might only happen on Windows. So I tried it on Unbunt 22.04.2 LTS, and got the following error. There are some other errors before `App running`, but I think it's not the problem. At the end, the same error `JS Error => [object Event]` like in Windows.
```
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
2024-10-07 16:50:15.369 (   0.142s) [    72EAA7D97440]vtkXOpenGLRenderWindow.:639   WARN| vtkXOpenGLRenderWindow (0x19f58d0): Cannot create GLX context.
2024-10-07 16:50:15.369 (   0.142s) [    72EAA7D97440]vtkOpenGLRenderWindow.c:794   WARN| vtkXOpenGLRenderWindow (0x19f58d0): Failed to initialize OpenGL functions!
2024-10-07 16:50:15.369 (   0.142s) [    72EAA7D97440]vtkOpenGLRenderWindow.c:813   WARN| vtkXOpenGLRenderWindow (0x19f58d0): Unable to find a valid OpenGL 3.2 or later implementation. Please update your video card driver to the latest version. If you are using Mesa please make sure you have version 11.2 or later and make sure your driver in Mesa supports OpenGL 3.2 such as llvmpipe or openswr. If you are on windows and using Microsoft remote desktop note that it only supports OpenGL 3.2 with nvidia quadro cards. You can use other remoting software such as nomachine to avoid this issue.

App running at:
 - Local:   http://localhost:8080/
 - Network: http://127.0.0.1:8080/

Note that for multi-users you need to use and configure a launcher.
And to prevent your browser from opening, add '--server' to your command line.
 JS Error => [object Event]
```
It might be my installation problem? Here is how I create the running environment:
```
pip install trame trame-vtklocal trame-vuetify trame-vtk
pip install "vtk==9.3.20240921.dev0" --extra-index-url https://wheels.vtk.org
```

**Comment by jourdain** [comment]
You can not go back on older version of vtk. trame-vtklocal is keeping up with the improvement we do on the VTK side. Once we reach the release (9.4), things will be more stable. 

It seems that you have some rendering issue. Wondering if that could be the issue on your system?

What is the real JS error in the browser?

**Comment by Jimmy-KL** [comment]
I checked and found the following error:
```
Request URL: http://localhost:3355/__trame_vtklocal/wasm/9.3.20240921/vtkWasmSceneManager.mjs
Request Method: GET
Status Code: 404 Not Found
Remote Address: [::1]:3355
Referrer Policy: strict-origin-when-cross-origin
```
A file is missing on my computer, but the reinstallation of the packages and creating a new venv cannot solve the problem. The strange thing is that another of my computer failed too with the same problem.
I checked the trame_vtklocal package, there is nothing under the folder `trame_vtklocal/module/serve/wasm/9.3.20240921`.

![jslost](https://github.com/user-attachments/assets/5a92efc2-12ef-4d60-8afa-67a1e44f45e5)

**Comment by jourdain** [comment]
Try to delete that `9.3.*` directory. Normally when you restart the app, the directory should be created and filled with the wasm files.

**Comment by Jimmy-KL** [comment]
I deleted `9.3.*` and it's working. Thanks!
Then I did some tests and found 2 problems:
1. In the pyvista examples, I tried to use `off_screen=True` for the `plotter` to disable the vtk window that popped up. The mesh was shown in the browser but it seems it's a static picture, you can not rotate or zoom in and out. Is it a bug or something that is not ready?
2. I tried the example `pyvista/drap2dsurf.py` which is a big mesh and when I tried to rotate it, it was a bit slow. Then I found that only the GPU of Intel was used on my computer, GPU from NVIDIA was not used. I did set the chrome browser to use NVIDIA and tried another 3D web app, the setting is OK. I'm wondering whether it's something related to webGPU? From what I know, the wasm can use something called webGPU.

![GPU usage](https://github.com/user-attachments/assets/94cf90d9-6034-4d87-a7ac-a06a1e8897e2)

**Comment by jourdain** [comment]
For 2, we haven't switch to WebGPU yet so it is just related to your system configuration / gpu selection.

**Comment by jourdain** [comment]
For 1, I tried in pure VTK to call `render_window.OffScreenRenderingOn()` and everything works as expected, but when doing it in PyVista, indeed the interaction stop working. 

It is an issue with PyVista (probably skipping interactor setup for off_screen), but if you do the following, it will just work

```python
plotter_inst.ren_win.OffScreenRenderingOn()
```

**Comment by Jimmy-KL** [comment]
Thanks, everything works fine now!
