### ISSUE TITLE
Remote rendering camera model not handling other interaction styles well

### ISSUE THREAD

**Issue by banesullivan** [Kitware/trame-vtklocal#6]
When using `vtkInteractorStyleTerrain`, trame-vtk's remote view seems to push past the limits of the viewup vector and cause weird behavior.

This results in a ton of warnings in the form of `vtkOpenGLRenderer (0x5bd19a1fefe0): Resetting view-up since view plane normal is parallel` and the axes orientation widgets jump to positions as shown in video below

I'm wondering if there is a way to improve this

```py
import pyvista as pv
from pyvista import examples
mesh = examples.load_random_hills()
pl = pv.Plotter()
pl.add_mesh(mesh)
pl.add_axes()
pl.enable_terrain_style()
pl.show()
```

https://github.com/Kitware/trame-vtklocal/assets/22067021/2ef26030-7768-426e-92f3-2c35b3ddac98

**Comment by jourdain** [comment]
Are you saying that if you were to use the native view (no trame, just vtk), you don't have any issue?

**Comment by banesullivan** [comment]
Correct, the native view does not have any issues

**Comment by banesullivan** [comment]
I just checked the native view and turns out it is having issues too... This must be an upstream VTK issue.

Sorry for the noise, I thought I had checked the native view before opening this issue.

I'll open an issue upstream in VTK about this
